/**
 * The `.well-known/x402` ownership document, and what matching it means.
 *
 * ## What a match proves
 *
 * That the controller of the resource's HTTPS origin declares this resource may
 * be catalogued against this `payTo` on this network. That is the whole claim.
 *
 * It does **not** prove wallet control: nothing here is signed by the `payTo`
 * key, so an origin can name an address it does not hold. It does not prove
 * resource ownership in any legal sense, it does not prove seller solvency, and
 * it says nothing at all about whether a payment will be honoured. The live 402
 * remains the payment authority. Every comment, document and label in this
 * feature uses that wording, because the failure mode of domain binding is
 * people believing it proved more than it did.
 *
 * ## This schema is ours
 *
 * There is no upstream `.well-known/x402` ownership convention. Checked against
 * `x402-foundation/x402` at `167a828e` on 2026-08-16: the path appears in no
 * merged spec. Two open proposals do touch it, and they shaped this file:
 *
 *   **#2979** (open, 2026-08-10) proposes `/.well-known/x402` as a *facilitator*
 *   manifest, with an `x402Version` and — importantly — a `kind` discriminator.
 *   **#2646** (draft, "DO NOT MERGE") proposes `/.well-known/x402.json` as a
 *   per-origin resource manifest generated by the middleware.
 *
 * Neither covers ownership authorisation. Rather than claim the path outright,
 * this document carries a `kind` of its own and the reader ignores anything it
 * does not recognise. A host serving #2979's facilitator manifest at this path
 * therefore yields `RESOURCE_NOT_DECLARED` — an honest "this origin did not say
 * so" — instead of a parse error or, worse, a false match.
 *
 * Published as an **x402Seek implementation convention**. Not a standard.
 */

/** The only document version this reader understands. */
export const DOCUMENT_VERSION = 1;

/**
 * Our discriminator, borrowed from #2979's shape so the path can hold more than
 * one kind of statement without either reader guessing.
 */
export const DOCUMENT_KIND = "resource-ownership";

/** Where the document lives, relative to the resource's own origin. */
export const WELL_KNOWN_PATH = "/.well-known/x402";

/** One authorisation: this resource, this payee, this network. Nothing else. */
export interface OwnershipEntry {
  resource: string;
  payTo: string;
  network: string;
}

export interface OwnershipDocument {
  version: number;
  kind: string;
  resources: OwnershipEntry[];
}

/**
 * Closed result set.
 *
 * Every one of these is a reason we wrote. An upstream error string is logged
 * for an operator and never persisted or returned, because a third party's
 * error text is the last thing that should reach a public field.
 */
export const VERIFICATION_REASONS = [
  "VERIFIED",
  "WELL_KNOWN_NOT_FOUND",
  "WELL_KNOWN_INVALID",
  "RESOURCE_NOT_DECLARED",
  "PAYTO_MISMATCH",
  "NETWORK_MISMATCH",
  "UNSAFE_ORIGIN",
  "FETCH_TIMEOUT",
  "FETCH_TOO_LARGE",
  "REDIRECT_REFUSED",
] as const;

export type VerificationReason = (typeof VERIFICATION_REASONS)[number];

/**
 * Reasons that mean "the origin contradicted us", as opposed to "the origin did
 * not say".
 *
 * The distinction is the whole of the precedence rule in the store. Silence is
 * not denial: a seller who never published a document, or whose server was down,
 * has not repudiated anything and keeps whatever binding they had. A seller who
 * published a document naming a different payee has.
 */
export function isContradiction(reason: VerificationReason): boolean {
  return reason === "PAYTO_MISMATCH" || reason === "NETWORK_MISMATCH";
}

/**
 * Parse a document, refusing anything unfamiliar rather than guessing.
 *
 * An unknown `version` or `kind` is not an error in the document's own terms —
 * it may be perfectly valid for some other reader — so it comes back as "this
 * is not a document I can act on" and the caller treats it as silence.
 */
export function parseDocument(text: string): OwnershipDocument | undefined {
  let raw: unknown;
  try {
    raw = JSON.parse(text);
  } catch {
    return undefined;
  }
  if (typeof raw !== "object" || raw === null || Array.isArray(raw)) return undefined;

  const doc = raw as Record<string, unknown>;
  if (doc.version !== DOCUMENT_VERSION) return undefined;
  if (doc.kind !== DOCUMENT_KIND) return undefined;
  if (!Array.isArray(doc.resources)) return undefined;

  const resources: OwnershipEntry[] = [];
  for (const item of doc.resources) {
    if (typeof item !== "object" || item === null) continue;
    const entry = item as Record<string, unknown>;
    if (
      typeof entry.resource !== "string" ||
      typeof entry.payTo !== "string" ||
      typeof entry.network !== "string"
    ) {
      continue;
    }
    resources.push({ resource: entry.resource, payTo: entry.payTo, network: entry.network });
  }
  return { version: DOCUMENT_VERSION, kind: DOCUMENT_KIND, resources };
}

/**
 * Compare a resource URL for identity.
 *
 * Case-folds the scheme and host because DNS is case-insensitive, and drops a
 * default port because `https://h/x` and `https://h:443/x` are the same
 * resource. Nothing else is normalised: path case and trailing slashes are
 * meaningful to an HTTP server and treating them as equal would let a
 * declaration cover a route its author did not write.
 */
export function sameResource(a: string, b: string): boolean {
  const norm = (value: string): string | undefined => {
    let url: URL;
    try {
      url = new URL(value);
    } catch {
      return undefined;
    }
    const port = url.port && url.port !== "443" ? `:${url.port}` : "";
    return `${url.protocol.toLowerCase()}//${url.hostname.toLowerCase()}${port}${url.pathname}${url.search}`;
  };
  const left = norm(a);
  const right = norm(b);
  return left !== undefined && left === right;
}

export interface MatchQuery {
  resource: string;
  payTo: string;
  network: string;
}

/**
 * Decide what the document says about one listing.
 *
 * Order matters and is deliberate: a document that never mentions the resource
 * is silence, and only a document that *does* mention it can contradict. Within
 * a mentioned resource, network is checked before payee so a testnet
 * declaration is never read as a pubnet authorisation.
 */
export function matchDocument(
  doc: OwnershipDocument,
  query: MatchQuery,
): Extract<
  VerificationReason,
  "VERIFIED" | "RESOURCE_NOT_DECLARED" | "PAYTO_MISMATCH" | "NETWORK_MISMATCH"
> {
  const forResource = doc.resources.filter((entry) => sameResource(entry.resource, query.resource));
  if (forResource.length === 0) return "RESOURCE_NOT_DECLARED";

  const forNetwork = forResource.filter((entry) => entry.network === query.network);
  if (forNetwork.length === 0) return "NETWORK_MISMATCH";

  // Several payees may be authorised for one resource on one network. Any of
  // them matching is an authorisation.
  if (forNetwork.some((entry) => entry.payTo === query.payTo)) return "VERIFIED";
  return "PAYTO_MISMATCH";
}
