/**
 * Provision three funded Stellar testnet accounts for the E-06 run.
 *
 * buyer      — signs the Soroban auth entry and pays
 * seller     — `payTo`, receives the payment
 * facilitator— sponsors the network fee and submits the invocation
 *
 * Writes `.env.e2e` (gitignored). Testnet only: friendbot refuses to fund a
 * pubnet account, and nothing here is ever pointed at pubnet.
 *
 * Asset: the native XLM Stellar Asset Contract. Chosen because friendbot funds
 * it directly, so the run is autonomous and needs no external faucet or
 * trustline setup. Every other SEP-41 asset — USDC included — is a one-line
 * config change (`E2E_ASSET`), which is what RFP §3.1's "any SEP-41 token,
 * USDC by default" asks for. See the caveat recorded with E-06 in the evidence
 * log.
 */

import { writeFileSync } from "node:fs";
import { Asset, Keypair, Networks, rpc } from "@stellar/stellar-sdk";

const FRIENDBOT = "https://friendbot.stellar.org";
const RPC_URL = process.env.STELLAR_RPC_URL ?? "https://soroban-testnet.stellar.org";

async function fund(publicKey: string, role: string): Promise<void> {
  const response = await fetch(`${FRIENDBOT}?addr=${encodeURIComponent(publicKey)}`);
  if (!response.ok) {
    throw new Error(`friendbot failed for ${role} ${publicKey}: ${response.status}`);
  }
  console.log(`  funded ${role.padEnd(11)} ${publicKey}`);
}

async function main(): Promise<void> {
  const buyer = Keypair.random();
  const seller = Keypair.random();
  const facilitator = Keypair.random();

  console.log("provisioning stellar:testnet accounts via friendbot");
  await fund(buyer.publicKey(), "buyer");
  await fund(seller.publicKey(), "seller");
  await fund(facilitator.publicKey(), "facilitator");

  const asset = Asset.native().contractId(Networks.TESTNET);
  const server = new rpc.Server(RPC_URL);
  const ledger = await server.getLatestLedger();

  console.log(`  native SAC   ${asset}`);
  console.log(`  ledger       ${ledger.sequence}`);

  const env = [
    "# Generated by apps/e2e-stellar provision. Testnet only. Gitignored.",
    `E2E_BUYER_SECRET=${buyer.secret()}`,
    `E2E_BUYER_ADDRESS=${buyer.publicKey()}`,
    `E2E_SELLER_SECRET=${seller.secret()}`,
    `E2E_SELLER_ADDRESS=${seller.publicKey()}`,
    `E2E_FACILITATOR_SECRET=${facilitator.secret()}`,
    `E2E_FACILITATOR_ADDRESS=${facilitator.publicKey()}`,
    `E2E_ASSET=${asset}`,
    "E2E_AMOUNT=10000",
    `STELLAR_RPC_URL=${RPC_URL}`,
    "",
  ].join("\n");

  writeFileSync(new URL("../.env.e2e", import.meta.url), env);
  console.log("wrote apps/e2e-stellar/.env.e2e");
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
